moirrra:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: community
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    port: 465
    username: 736043695@qq.com
    password: mjjnwgwpqtnnbfdi
  community:
    path:
      domain: http://localhost:8080
      upload: d:/code/projects/data/community/upload
    multipart:
        max-file-size: 5
        max-request-size: 50
  redis:
    database: 11
    host: localhost
    port: 6379
    password: 123456