# Server
server:
  port: 8080
  servlet:
    context-path: /community

spring:
  profiles:
    active: dev
  # Thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/template/
    suffix: .html
  # DataSource
  datasource:
    driver-class-name: ${moirrra.datasource.driver-class-name}
    url: jdbc:mysql://${moirrra.datasource.host}:${moirrra.datasource.port}/${moirrra.datasource.database}?characterEncoding=utf-8&useSSL=false&serverTimeZone=Shanghai
    username: ${moirrra.datasource.username}
    password: ${moirrra.datasource.password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: ${moirrra.mail.host}
    port: ${moirrra.mail.port}
    username: ${moirrra.mail.username}
    password: ${moirrra.mail.password}
    properties.mail.smtp.ssl.enable: true
  servlet:
    multipart:
      max-file-size: ${moirrra.community.multipart.max-file-size}MB
      max-request-size: ${moirrra.community.multipart.max-request-size}MB
  redis:
    database: ${moirrra.redis.database}
    host: ${moirrra.redis.host}
    port: ${moirrra.redis.port}
    password: ${moirrra.redis.password}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group # consumer.properties
      enable-auto-commit: true
      auto-commit-interval: 3000
  # Elastic search
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: 127.0.0.1:9200
    connection-timeout: 20000ms
  # Quartz
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org.quartz:
        scheduler:
          instanceId: AUTO
        jobStore:
          # 下面的 2.5.6之后不再支持
          # class: org.quartz.impl.jdbcjobstore.JobStoreTX
          class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          isClustered: true
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 5


# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.moirrra.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

logging:
  level:
    com.moirrra.community: debug
#  file:
#    name: D:/code/projects/logs/community/community.log

# community
community:
  path:
    domain: ${moirrra.community.path.domain}
    upload: ${moirrra.community.path.upload}

# wk
wk:
  image:
    command: d:/code/wkhtmltopdf/bin/wkhtmltoimage
    storage: d:/code/projects/data/community/wk-images

